import Chapter1DyadicConditional

open MeasureTheory Set
namespace Asakura.Chapter1Complete

/-- The information generated by successively longer finite prefixes increases. -/
theorem finite_prefix_information_monotone {Ω E : Type*} [MeasurableSpace E]
    (X : ℕ → Ω → E) :
    Monotone (fun n => MeasurableSpace.comap (fun w (i : Fin n) => X i w) inferInstance) := by
  intro n m hnm
  let r : (Fin m → E) → (Fin n → E) := fun v i => v ⟨i,lt_of_lt_of_le i.isLt hnm⟩
  have hr : Measurable r := measurable_pi_iff.mpr fun _ => measurable_pi_apply _
  have hc : (fun w (i : Fin n) => X i w)=r ∘ (fun w (i : Fin m) => X i w) := rfl
  dsimp only
  rw [hc,← MeasurableSpace.comap_comp]
  exact MeasurableSpace.comap_mono hr.comap_le

theorem binary_information_filtration :
    Monotone (fun n => MeasurableSpace.comap (dyadicPrefix n) inferInstance) :=
  finite_prefix_information_monotone dyadicDigit

end Asakura.Chapter1Complete
