import Chapter5CylinderDensity
import Mathlib.Topology.Sequences

open MeasureTheory Set Filter TopologicalSpace
open scoped Topology
namespace Asakura.Chapter5

/-- Continuity makes a countable dense set of times generate the whole
process sigma algebra; this is an equality, not a generation assumption. -/
theorem continuous_process_countable_sigma {Ω K E : Type*}
    [TopologicalSpace K] [FirstCountableTopology K]
    [TopologicalSpace E] [PseudoMetrizableSpace E]
    [MeasurableSpace E] [BorelSpace E]
    (W : K → Ω → E) (hW : ∀ w, Continuous (fun t => W t w))
    (q : ℕ → K) (hq : DenseRange q) :
    MeasurableSpace.comap (fun w t => W t w) inferInstance =
      MeasurableSpace.comap (fun w n => W (q n) w) inferInstance := by
  apply le_antisymm
  · letI : MeasurableSpace Ω := MeasurableSpace.comap (fun w n => W (q n) w) inferInstance
    apply Measurable.comap_le
    apply Measurable.of_eval
    intro t
    obtain ⟨s,hs,hst⟩ := mem_closure_iff_seq_limit.mp (hq t)
    choose k hk using hs
    have hm n : Measurable (W (s n)) := by
      rw [← hk n]
      exact (measurable_pi_apply (k n)).comp (Measurable.of_comap_le (f := fun w n => W (q n) w) le_rfl)
    exact measurable_of_tendsto_metrizable hm
      (tendsto_pi_nhds.mpr fun w => (hW w).continuousAt.tendsto.comp hst)
  · letI : MeasurableSpace Ω := MeasurableSpace.comap (fun w t => W t w) inferInstance
    apply Measurable.comap_le
    exact Measurable.of_eval fun n =>
      (measurable_pi_apply (q n)).comp (Measurable.of_comap_le (f := fun w t => W t w) le_rfl)

/-- Finite prefixes of the countable vector increase to its sigma algebra. -/
theorem prefix_coordinate_sigma {Ω E : Type*} [MeasurableSpace E]
    (W : ℕ → Ω → E) :
    (⨆ n : ℕ, MeasurableSpace.comap (fun w (i : Fin n) => W i w) inferInstance) =
      MeasurableSpace.comap (fun w n => W n w) inferInstance := by
  apply le_antisymm
  · apply iSup_le
    intro n
    letI : MeasurableSpace Ω := MeasurableSpace.comap (fun w n => W n w) inferInstance
    apply Measurable.comap_le
    exact Measurable.of_eval fun i =>
      (measurable_pi_apply i.val).comp (Measurable.of_comap_le (f := fun w n => W n w) le_rfl)
  · letI : MeasurableSpace Ω :=
      ⨆ n : ℕ, MeasurableSpace.comap (fun w (i : Fin n) => W i w) inferInstance
    apply Measurable.comap_le
    apply Measurable.of_eval
    intro n
    exact (measurable_pi_apply (⟨n,Nat.lt_succ_self n⟩ : Fin (n+1))).comp
      (Measurable.of_comap_le (le_iSup
        (fun k => MeasurableSpace.comap (fun w (i : Fin k) => W i w) inferInstance) (n+1)))

theorem prefix_coordinate_monotone {Ω E : Type*} [MeasurableSpace E]
    (W : ℕ → Ω → E) :
    Monotone (fun n : ℕ => MeasurableSpace.comap (fun w (i : Fin n) => W i w) inferInstance) := by
  intro n k hnk
  letI : MeasurableSpace Ω := MeasurableSpace.comap (fun w (i : Fin k) => W i w) inferInstance
  apply Measurable.comap_le
  exact Measurable.of_eval fun i =>
    (measurable_pi_apply (⟨i.val,i.isLt.trans_le hnk⟩ : Fin k)).comp
      (Measurable.of_comap_le (f := fun w (i : Fin k) => W i w) le_rfl)

open scoped ContDiff

/-- The full density step of the representation proof, for the actual
sigma algebra generated by a continuous finite-dimensional process. -/
theorem continuous_process_smooth_cylinder_density {Ω K E : Type*} [MeasurableSpace Ω]
    [TopologicalSpace K] [FirstCountableTopology K]
    [NormedAddCommGroup E] [NormedSpace ℝ E] [FiniteDimensional ℝ E]
    [MeasurableSpace E] [BorelSpace E]
    (P : Measure Ω) [IsProbabilityMeasure P]
    (W : K → Ω → E) (hWm : ∀ t, Measurable (W t))
    (hWc : ∀ w, Continuous (fun t => W t w))
    (q : ℕ → K) (hq : DenseRange q) (U : Lp ℝ 2 P)
    (hU : AEStronglyMeasurable[MeasurableSpace.comap (fun w t => W t w) inferInstance] U P)
    (ε : ℝ) (hε : 0 < ε) :
    ∃ (n : ℕ) (g : (Fin n → E) → ℝ)
      (hg : MemLp (fun w => g (fun i => W (q i) w)) 2 P),
      HasCompactSupport g ∧ ContDiff ℝ ∞ g ∧
      ‖U - hg.toLp (fun w => g (fun i => W (q i) w))‖ < ε := by
  have he := continuous_process_countable_sigma W hWc q hq
  rw [he,← prefix_coordinate_sigma (fun n => W (q n))] at hU
  exact cylinder_approximation_of_generating_vectors P (fun n => Fin n → E)
    (fun n w i => W (q i) w) (fun n => Measurable.of_eval fun i => hWm (q i))
    (prefix_coordinate_monotone (fun n => W (q n))) U hU ε hε

end Asakura.Chapter5
