import Chapter12IndependentConditionalIntegral
import Chapter12ProductTrim

open MeasureTheory ProbabilityTheory Set
namespace Asakura.Chapter12
set_option backward.isDefEq.respectTransparency false
set_option maxHeartbeats 1800000

/-- Conditional integration for an entire information sigma algebra,
not merely for the sigma algebra generated by the current finite state. -/
theorem independent_sigma_integral {Ω E : Type*} [m : MeasurableSpace Ω] [mE : MeasurableSpace E]
    (P : Measure Ω) [IsProbabilityMeasure P] (F : MeasurableSpace Ω) (hle : F≤m)
    (Y : Ω → E) (hY : Measurable[m] Y) (ν : Measure E) [IsProbabilityMeasure ν]
    (hlaw : @HasLaw Ω E m mE Y ν P) (hind : Indep (MeasurableSpace.comap Y mE) F P)
    (f : Ω × E → ℝ) (hf : @Measurable _ _ (F.prod mE) inferInstance f)
    (hi : Integrable[F.prod mE] f
      (@Measure.prod Ω E F mE (P.trim hle) ν)) :
    P[(fun w => f (w,Y w))|F]=ᵐ[P] (fun w => ∫ y,f (w,y) ∂ν) := by
  letI := @probability_trim Ω m P _ F hle
  have hid := @trim_identity_preserving Ω m P F hle
  have hInd : @IndepFun Ω Ω E m F mE id Y P := by
    change Indep (MeasurableSpace.comap id F) (MeasurableSpace.comap Y mE) P
    simpa only [MeasurableSpace.comap_id] using hind.symm
  have he := @independent_conditional_integral Ω Ω E m F mE P _ (P.trim hle) ν _ _
    id Y (@MeasurePreserving.measurable Ω Ω m F id P (P.trim hle) hid) hY
      (@MeasurePreserving.hasLaw Ω Ω m F id (P.trim hle) P hid) hlaw hInd f hf hi
  simpa only [MeasurableSpace.comap_id,id_eq] using he

end Asakura.Chapter12
#print axioms Asakura.Chapter12.independent_sigma_integral
