import Appendix

open MeasureTheory Filter Set
open scoped Topology ENNReal
namespace Asakura

section Measurability
variable {Ω S T : Type*} [MeasurableSpace Ω]

theorem continuous_measurable [TopologicalSpace S] [TopologicalSpace T]
    [MeasurableSpace S] [MeasurableSpace T] [BorelSpace S] [BorelSpace T]
    {f : S → T} (hf : Continuous f) : Measurable f := hf.measurable

theorem product_borel [TopologicalSpace S] [TopologicalSpace T]
    [SecondCountableTopology S] [SecondCountableTopology T]
    [MeasurableSpace S] [MeasurableSpace T] [BorelSpace S] [BorelSpace T] :
    (inferInstance : MeasurableSpace (S × T)) = borel (S × T) :=
  BorelSpace.measurable_eq

theorem measurable_sum_product {f g : Ω → ℝ} (hf : Measurable f) (hg : Measurable g) :
    Measurable (fun x => f x + g x) ∧ Measurable (fun x => f x * g x) :=
  ⟨hf.add hg, hf.mul hg⟩

theorem measurable_signed_sup_inf (f : ℕ → Ω → EReal) (hf : ∀ n, Measurable (f n)) :
    Measurable (fun x => ⨆ n, f n x) ∧ Measurable (fun x => ⨅ n, f n x) :=
  ⟨.iSup hf, .iInf hf⟩

theorem monotone_real_measurable {f : ℝ → ℝ} (hf : Monotone f ∨ Antitone f) :
    Measurable f := hf.elim Monotone.measurable Antitone.measurable

theorem nonnegative_integral_mono (μ : Measure Ω) {f g : Ω → ℝ≥0∞} (h : f ≤ g) :
    ∫⁻ x, f x ∂μ ≤ ∫⁻ x, g x ∂μ := lintegral_mono h

theorem nonnegative_integral_add (μ : Measure Ω) {f g : Ω → ℝ≥0∞}
    (hf : Measurable f) :
    ∫⁻ x, (f x + g x) ∂μ = (∫⁻ x, f x ∂μ) + ∫⁻ x, g x ∂μ :=
  lintegral_add_left hf g
end Measurability

/-- A.5: the manuscript's augmentation, as an actual measurable space. -/
@[instance_reducible] def nullAugmentation {Ω : Type*} [m : MeasurableSpace Ω] (μ : Measure Ω)
    (G : MeasurableSpace Ω) : MeasurableSpace Ω where
  MeasurableSet' A := MeasurableSet[m] A ∧ ∃ B, MeasurableSet[G] B ∧ A =ᵐ[μ] B
  measurableSet_empty := ⟨@MeasurableSet.empty Ω m, ∅, @MeasurableSet.empty Ω G, Filter.EventuallyEq.rfl⟩
  measurableSet_compl := by
    rintro A ⟨hA, B, hB, hAB⟩
    refine ⟨hA.compl, Bᶜ, hB.compl, ?_⟩
    filter_upwards [hAB] with x hx
    simpa only [Set.mem_compl_iff] using congrArg Not hx
  measurableSet_iUnion := by
    intro A hA
    choose hAm B hBm hAB using hA
    refine ⟨MeasurableSet.iUnion hAm, ⋃ n, B n, MeasurableSet.iUnion hBm, ?_⟩
    have h : ∀ᵐ x ∂μ, ∀ n, x ∈ A n ↔ x ∈ B n :=
      (ae_all_iff).2 (fun n => (hAB n).mono (fun x hx => iff_of_eq hx))
    filter_upwards [h] with x hx
    simpa only [Set.mem_iUnion] using propext (exists_congr hx)

/-- The augmentation equals the sigma algebra generated by G and ambient null sets. -/
theorem nullAugmentation_minimal {Ω : Type*} [m : MeasurableSpace Ω]
    (μ : Measure Ω) (G : MeasurableSpace Ω) (hG : G ≤ m) :
    nullAugmentation (m := m) μ G = MeasurableSpace.generateFrom
      {A | MeasurableSet[G] A ∨ (MeasurableSet[m] A ∧ μ A = 0)} := by
  apply le_antisymm
  · rintro A ⟨hA, B, hB, hAB⟩
    have hdiff := ae_eq_set.mp hAB
    have hB' : MeasurableSet[MeasurableSpace.generateFrom
        {A | MeasurableSet[G] A ∨ (MeasurableSet[m] A ∧ μ A = 0)}] B :=
      MeasurableSpace.measurableSet_generateFrom (Or.inl hB)
    have hAB' : MeasurableSet[MeasurableSpace.generateFrom
        {A | MeasurableSet[G] A ∨ (MeasurableSet[m] A ∧ μ A = 0)}] (A \ B) :=
      MeasurableSpace.measurableSet_generateFrom (Or.inr ⟨hA.diff (hG _ hB), hdiff.1⟩)
    have hBA' : MeasurableSet[MeasurableSpace.generateFrom
        {A | MeasurableSet[G] A ∨ (MeasurableSet[m] A ∧ μ A = 0)}] (B \ A) :=
      MeasurableSpace.measurableSet_generateFrom (Or.inr ⟨(hG _ hB).diff hA, hdiff.2⟩)
    have heq : A = (A \ B) ∪ (B \ (B \ A)) := by ext x; simp; tauto
    rw [heq]
    exact hAB'.union (hB'.diff hBA')
  · apply MeasurableSpace.generateFrom_le
    rintro A (hA | ⟨hA, hzero⟩)
    · exact ⟨hG _ hA, A, hA, Filter.EventuallyEq.rfl⟩
    · refine ⟨hA, ∅, @MeasurableSet.empty Ω G, ae_eq_set.mpr ?_⟩
      simpa using And.intro hzero (measure_empty (μ := μ))

/-- Re-express the manuscript's sum-of-two-null-measures convention. -/
theorem nullAugmentation_membership {Ω : Type*} [m : MeasurableSpace Ω]
    (μ : Measure Ω) (G : MeasurableSpace Ω) (A : Set Ω) :
    MeasurableSet[nullAugmentation (m := m) μ G] A ↔ MeasurableSet[m] A ∧
      ∃ B, MeasurableSet[G] B ∧ μ (B \ A) + μ (A \ B) = 0 := by
  change (MeasurableSet[m] A ∧ ∃ B, MeasurableSet[G] B ∧ A =ᵐ[μ] B) ↔ _
  simp only [ae_eq_set, add_eq_zero, and_comm]

end Asakura
