import FullAuditPartitionCE

open MeasureTheory Set Filter Function
open scoped ENNReal
namespace Asakura.FullAudit

/-- The sigma algebra generated by finitely many indicators is the sigma
algebra generated by their sets; no completion of the sigma algebra is needed. -/
theorem indicator_generated_sigma {Ω ι : Type*} (A : ι → Set Ω) :
    (⨆ i, MeasurableSpace.comap ((A i).indicator (fun _ => (1:ℝ))) inferInstance) =
      MeasurableSpace.generateFrom (Set.range A) := by
  classical
  apply le_antisymm
  · refine iSup_le fun i => ?_
    have hm : Measurable[MeasurableSpace.generateFrom (Set.range A)] ((A i).indicator (fun _ => (1:ℝ))) :=
      measurable_const.indicator (MeasurableSpace.measurableSet_generateFrom (mem_range_self i))
    exact hm.comap_le
  · apply MeasurableSpace.generateFrom_le
    rintro E ⟨i,rfl⟩
    apply (le_iSup (fun j => MeasurableSpace.comap ((A j).indicator (fun _ => (1:ℝ))) inferInstance) i)
    have he : ((A i).indicator (fun _ => (1:ℝ))) ⁻¹' {1} = A i := by
      ext ω
      by_cases h : ω ∈ A i <;> simp [Set.indicator,h]
    have hh : MeasurableSet[MeasurableSpace.comap ((A i).indicator (fun _ => (1:ℝ))) inferInstance]
        (((A i).indicator (fun _ => (1:ℝ))) ⁻¹' {1}) :=
      ⟨{1},measurableSet_singleton _,rfl⟩
    rwa [he] at hh

/-- The finite-cell exercise under its exact probability-one covering condition.
The uncovered set can be nonempty; its integral vanishes because it is null. -/
theorem finite_cells_condExp {Ω ι : Type*} [Fintype ι] [m0 : MeasurableSpace Ω]
    (P : Measure Ω) [IsProbabilityMeasure P] (A : ι → Set Ω)
    (hA : ∀ i, MeasurableSet (A i)) (hd : Pairwise (Disjoint on A))
    (hcover : ∑ i, P (A i) = 1) {X : Ω → ℝ} (hX : Integrable X P) :
    (fun ω => ∑ i, (A i).indicator (fun _ => (P.real (A i))⁻¹ * ∫ x in A i, X x ∂P) ω) =ᵐ[P]
      P[X | ⨆ i, MeasurableSpace.comap ((A i).indicator (fun _ => (1:ℝ))) inferInstance] := by
  classical
  rw [indicator_generated_sigma]
  let m := MeasurableSpace.generateFrom (range A)
  let Y : Ω → ℝ := fun ω => ∑ i, (A i).indicator (fun _ => (P.real (A i))⁻¹ * ∫ x in A i, X x ∂P) ω
  letI : MeasurableSpace Ω := m0
  have hm : m ≤ m0 := MeasurableSpace.generateFrom_le (by rintro E ⟨i,rfl⟩; exact hA i)
  have hYm : Measurable[m] Y := Finset.measurable_sum _ (fun i _ =>
    measurable_const.indicator (MeasurableSpace.measurableSet_generateFrom (mem_range_self i)))
  have hYi : Integrable Y P := integrable_finsetSum _ (fun i _ => (integrable_const _).indicator (hA i))
  have hcell : ∀ i, ∫ ω in A i, Y ω ∂P = ∫ ω in A i, X ω ∂P := by
    intro i
    have hy : ∀ ω ∈ A i, Y ω = (P.real (A i))⁻¹ * ∫ x in A i, X x ∂P := by
      intro ω hω
      dsimp only [Y]
      rw [Finset.sum_eq_single i]
      · simp [hω]
      · intro j _ hji
        have hn : ω ∉ A j := fun hj => Set.disjoint_left.mp (hd hji) hj hω
        simp [hn]
      · simp
    rw [setIntegral_congr_fun (hA i) hy, setIntegral_const, smul_eq_mul]
    by_cases hz : P.real (A i) = 0
    · have hp : P (A i) = 0 := (measureReal_eq_zero_iff (measure_ne_top P _)).mp hz
      simp [hz,hp]
    · field_simp
  have hc : ∀ᵐ ω ∂P, ω ∈ ⋃ i, A i := by
    have hu : P (⋃ i, A i) = 1 := by rw [measure_iUnion hd hA, tsum_fintype,hcover]
    rw [ae_iff]
    change P (⋃ i, A i)ᶜ = 0
    rw [measure_compl (MeasurableSet.iUnion hA) (measure_ne_top _ _),hu,measure_univ,tsub_self]
  have htotal : ∫ ω, Y ω ∂P = ∫ ω, X ω ∂P := by
    rw [integral_eq_setIntegral hc Y,integral_eq_setIntegral hc X,
      integral_iUnion_fintype hA hd (fun _ => hYi.integrableOn),
      integral_iUnion_fintype hA hd (fun _ => hX.integrableOn)]
    exact Finset.sum_congr rfl (fun i _ => hcell i)
  have hpi : IsPiSystem (range A) := by
    rintro E ⟨i,rfl⟩ H ⟨j,rfl⟩ hne
    have hij : i=j := by
      by_contra h
      exact hne.ne_empty (Set.disjoint_iff_inter_eq_empty.mp (hd h))
    subst j
    simpa using mem_range_self i
  apply ae_eq_condExp_of_forall_setIntegral_eq hm hX
    (fun _ _ _ => hYi.integrableOn) _ hYm.aestronglyMeasurable
  intro B hB _
  refine MeasurableSpace.induction_on_inter (C := fun B _ => ∫ ω in B, Y ω ∂P = ∫ ω in B, X ω ∂P)
    rfl hpi ?_ ?_ ?_ ?_ B hB
  · simp
  · rintro E ⟨i,rfl⟩; exact hcell i
  · intro E hE he
    have hy := integral_add_compl (hm _ hE) hYi
    have hx := integral_add_compl (hm _ hE) hX
    linarith
  · intro E hd hme he
    rw [integral_iUnion (fun n => hm _ (hme n)) hd hYi.integrableOn,
      integral_iUnion (fun n => hm _ (hme n)) hd hX.integrableOn]
    exact tsum_congr he

end Asakura.FullAudit
